### ISSUE TITLE
Default client in the dropdown: "pick one" or the least used by default

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNodePackage-medalla-validator#12]
From discussion in [reddit](https://www.reddit.com/r/ethereum/comments/ihxulp/solution_to_client_diversity_problem_automatic/g34ns5y?utm_source=share&utm_medium=web2x&context=3): 

> It would be awesome if you changed the dropdown menu for client selection to automatically be the least used client as default. Per now prysm is default and you have to change it to lighthouse. But I think it would help if the default always is the least used client

Since it's really hard to know which one is the most used and the least used, an option to start with a "pick one" could be implemented.

**Comment by dapplion** [comment]
That's a great idea to motivate client diversity but this should be implemented through social channels not in code. As Lanski said it's not possible to know really what's the market share of a client.
