### ISSUE TITLE
wrong password

### ISSUE THREAD

**Issue by ligi** [dappnode/DAppNodePackage-medalla-validator#2]
I just installed the medalla package - but when trying to log in I see:

![Selection_125](https://user-images.githubusercontent.com/111600/89467843-a1452f00-d776-11ea-93f7-87b23ca71826.png)

But the problem is I used the same password (password manager) - I even repeated (uninstalled, installed again) - just to make sure.

Then I told my password manager to generate a password with no special chars and it worked. So I guess there is some escaping problem.

One of these characters must be the problem "EF$sNe_T>B5n)apczchF,(>je"

**Comment by emansipater** [comment]
I had this same problem too and was able to confirm that the escaping issue relates to the "$" symbol (at a minimum).

**Comment by dapplion** [comment]
@emansipater exactly! Since we use docker to manage secrets, the `$` character can cause issues as it's used for variable interpolation. I would recommend to sticking to alphanumeric passwords for maximum compatibility

**Comment by emansipater** [comment]
Not trying to make more work for you (honest!) but wouldn't best practice in this case be to detect when the user is attempting to set a password containing the "$" symbol and warn/reject? Or at bare minimum add some text to the page where the password is set noting that this character (and perhaps others) aren't supported?

**Comment by dapplion** [comment]
> Not trying to make more work for you (honest!) but wouldn't best practice in this case be to detect when the user is attempting to set a password containing the "$" symbol and warn/reject? Or at bare minimum add some text to the page where the password is set noting that this character (and perhaps others) aren't supported?

Agree, if the transition to Prysm's UI is slower than intended I'll add it for sure
