### ISSUE TITLE
Home GUI showing Current Slot in Epoch instead of Current Epoch

### ISSUE THREAD

**Issue by Hibero** [dappnode/DAppNodePackage-medalla-validator#4]
On https://github.com/dappnode/DAppNodePackage-medalla-validator/blob/e64c037d9819dba6ad4d948894fc163a61cbce31/build/ui/src/components/NodeStats.tsx#L14

I think it should be 
`nodeStats.chainhead.headSlot / nodeStats.chainhead.slotsPerEpoch` 
not 
`nodeStats.chainhead.headSlot % nodeStats.chainhead.slotsPerEpoch`

Probably should rounded down also?

**Comment by dapplion** [comment]
Now shows latest slot in the same fashion of all popular block explorers
